### ISSUE TITLE
error when field name is `r#type`.

### ISSUE THREAD

**Issue by droundy** [Ten0/serde_avro_fast#15]
I have a struct that looks like this:
```
#[derive(Debug, BuildSchema, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct KvLineKey {
    pub key: String,
    pub r#type: KvType,
    pub key_adgroups: Vec<KeyAdgroup>,
}
```
and when I look at the schema (with `{:#?}` formatting) I get:
```
Record(
    Record {
        fields: [
            RecordField {
                name: "key",
                schema: String,
            },
            RecordField {
                name: "r#type",
                schema: Enum(
                    Enum {
                        name: "sludge.logline.types.KvType",
                        symbols: [
                            "Prospecting",
                            "Retargeting",
                        ],
                    },
                ),
            },
            RecordField {
                name: "key_adgroups",
                schema: Array(
                    Record,
                ),
            },
        ],
        name: "sludge.logline.types.KvLineKey",
    },
)
```
which leads to errors because there is no field named `"r#type"`.

Let me know if you need more info, but I'm at the end of my work day.

**Comment by Ten0** [comment]
Would be nice to have the actual error to be sure, but it might be that serde interpretes r#type as just type, while BuildSchema doesn't.

**Comment by droundy** [comment]
I think you still need to do a new version release for `serde_avro_derive`?

**Comment by Ten0** [comment]
`cargo update` should get you the latest version of `serde_avro_derive_macros` as a dependency of `serde_avro_derive` due to the way the resolver works, no?

**Comment by droundy** [comment]
Oh, I see, I didn't notice that there was a new `serde_avro_derive_macros`.  That will indeed work.  I'd generally want to update the `serde_avro_derive` also so that we can easily specify that we want the version with the fix without also having to specify a `serde_avro_derive_macros` dependency.

**Comment by Ten0** [comment]
Alright done
